---
title: "Class Size"
author: "Lela Sengupta"
format: html
execute:
  echo: false
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(brms)
library(tidybayes)
library(gtsummary)
```

```{r}
#| label: load_data
class <- read_csv("STAR.csv", show_col_types = FALSE) 

class <- class %>%
  mutate(kinder = recode_factor(classtype,
                                `1` = "small",
                                `2` = "regular",
                                `3` = "regular with aid"),
         race = recode_factor(race,
                              `1` = "white",
                              `2` = "black",
                              `3` = "others",    # Combining Asian and Native American into 'others'
                              `4` = "hispanic",
                              `5` = "others",
                              `6` = "others")) |>
  filter(classtype %in% c(1,2)) %>%
  select(kinder, g4math, race) %>%
  drop_na()

```

```{r}
#| label: model
#| cache: true

fit_class <- brm(formula = g4math ~ kinder,
                 data = class,
                 family = gaussian(),
                 silent = 2,
                 refresh = 0,
                 seed = 12)
```

```{r}
#| label: plot
#| message: false

fit_class |> 
  add_predicted_draws(newdata = tibble(kinder = c("regular", "small"))) |> 
  ggplot(aes(x = .prediction)) +
  geom_histogram(aes(y = after_stat(count/sum(count))),
                 bins = 100)
```


```{r}
tbl_regression(fit_class)

fixef(fit_class)
```

`


